language: node_js
node_js:
  - 0.12.2
services:
  - mongodb
env:
  - TEST_DIR=backend
script: cd $TEST_DIR && npm install && gulp test
notifications:
  email: false
  slack: ios-tub:Xnz3RLZYq8cEh0GA6Czq9fd6
cache:
  directories:
    - backend/node_modules
